/**
 * In-memory cache with deduplication for gh CLI calls.
 *
 * Reduces GitHub API rate limit usage by:
 * 1. Caching responses with operation-specific TTL
 * 2. Deduplicating concurrent identical requests
 * 3. Invalidating cache after write operations
 *
 * Design notes:
 * - No periodic sweep: Expired entries are only removed when accessed via get() or
 *   during explicit invalidation. This is acceptable for the typical workload where
 *   the same PRs/operations are accessed repeatedly within the TTL window.
 * - Large cache keys: Keys are generated by joining args with colons, which can
 *   create large keys for GraphQL queries. This is a tradeoff for simplicity;
 *   hashing could be added if memory becomes a concern.
 */

interface CacheEntry<T> {
  value: T;
  expiresAt: number;
}

export class GhCache {
  private cache = new Map<string, CacheEntry<unknown>>();
  private pendingRequests = new Map<string, Promise<unknown>>();

  /**
   * TTL per operation (milliseconds)
   *
   * - prChecks: 15s - CI status changes frequently, but 15s is fast enough
   * - prView: 30s - PR metadata (title, state, reviewDecision) changes infrequently
   * - default: 30s - Conservative default for unknown operations (including api/graphql)
   *
   * Note: reviewDecision and comments use prView/default TTL respectively since
   * they're fetched via `gh pr view` and `gh api graphql`.
   */
  private readonly TTL = {
    prChecks: 15_000, // CI checks - frequent changes
    prView: 30_000, // PR metadata (including reviewDecision) - infrequent changes
    default: 30_000,
  };

  /**
   * Generate a unique cache key from gh CLI arguments.
   *
   * @example
   * key(["pr", "view", "123", "--json", "state"])
   * // Returns: "gh:pr:view:123:--json:state"
   */
  key(args: string[]): string {
    return `gh:${args.join(":")}`;
  }

  /**
   * Get TTL (time-to-live) for a specific gh operation.
   *
   * Analyzes the command structure to determine appropriate TTL.
   */
  getTTL(args: string[]): number {
    const cmd = args[0];
    if (cmd === "pr") {
      const sub = args[1];
      if (sub === "checks") return this.TTL.prChecks;
      if (sub === "view") return this.TTL.prView;
    }
    return this.TTL.default;
  }

  /**
   * Get a cached value if it exists and hasn't expired.
   *
   * @param key - Cache key generated by key()
   * @returns Cached value or null if not found/expired
   */
  get<T>(key: string): T | null {
    const entry = this.cache.get(key);
    if (!entry) return null;

    if (Date.now() > entry.expiresAt) {
      this.cache.delete(key);
      return null;
    }

    return entry.value as T;
  }

  /**
   * Store a value in the cache with expiration.
   *
   * @param key - Cache key generated by key()
   * @param value - Value to cache
   * @param ttlMs - Time-to-live in milliseconds
   */
  set<T>(key: string, value: T, ttlMs: number): void {
    this.cache.set(key, {
      value,
      expiresAt: Date.now() + ttlMs,
    });
  }

  /**
   * Deduplicate concurrent requests for the same cache key.
   *
   * When multiple callers request the same data simultaneously,
   * only the first caller executes the API call. Subsequent callers
   * await the same Promise.
   *
   * @param key - Cache key for the request
   * @param fn - Function that performs the API call
   * @returns Result from the first execution, shared by all callers
   *
   * @example
   * // 5 agents request PR #123 simultaneously
   * // Only 1 gh CLI call is made, all 5 get the same result
   * await dedupe("gh:pr:view:123", () => gh(["pr", "view", "123"]))
   */
  async dedupe<T>(key: string, fn: () => Promise<T>): Promise<T> {
    const existing = this.pendingRequests.get(key);
    if (existing) {
      return existing as Promise<T>;
    }

    const promise = fn().finally(() => this.pendingRequests.delete(key));
    this.pendingRequests.set(key, promise);
    return promise;
  }

  /**
   * Invalidate all cache entries for a specific PR.
   *
   * Call this after write operations (merge, close, assign) to ensure
   * the cache doesn't return stale data.
   *
   * Matches multiple key patterns:
   * - `gh:pr:view:123:` - from `gh pr view 123`
   * - `number=123` - from `gh api graphql ... -F number=123`
   * - `pulls/123/comments` - from `gh api repos/.../pulls/123/comments`
   *
   * @param pr - PR to invalidate cache for
   */
  invalidatePR(pr: { owner: string; repo: string; number: number }): void {
    const repoStr = `${pr.owner}/${pr.repo}`;
    const prNum = String(pr.number);
    const prNumPatterns = [
      `:${prNum}:`, // Matches `gh:pr:view:123:--repo:owner/repo:...`
      `:-F:number=${prNum}:`, // Matches GraphQL `...-F number=123` (capital F)
      `:-f:number=${prNum}:`, // Matches GraphQL `...-f number=123` (lowercase f)
      `number=${prNum}&`, // Matches URL params `...&number=123&`
      `/pulls/${prNum}/`, // Matches REST API `repos/.../pulls/123/comments`
    ];

    Array.from(this.cache.keys()).forEach((key) => {
      // Match repo in multiple formats:
      // - `--repo:owner/repo` for CLI commands
      // - `/owner/repo/` for REST API URLs
      // - `owner=owner` and `name=repo` for GraphQL queries
      const hasRepo =
        key.includes(`--repo:${repoStr}`) ||
        key.includes(`/${repoStr}/`) ||
        (key.includes(`owner=${pr.owner}`) && key.includes(`name=${pr.repo}`));

      const hasPrNum = prNumPatterns.some((p) => key.includes(p));
      if (hasRepo && hasPrNum) {
        this.cache.delete(key);
      }
    });
  }

  /**
   * Invalidate all cache entries for a specific repository.
   *
   * Useful for bulk operations or webhook-driven invalidation.
   *
   * Matches keys containing:
   * - `--repo:owner/repo` for CLI commands
   * - `/owner/repo/` for REST API URLs
   * - `owner=owner` and `name=repo` for GraphQL queries
   *
   * @param owner - Repository owner
   * @param repo - Repository name
   */
  invalidateRepo(owner: string, repo: string): void {
    const repoStr = `${owner}/${repo}`;
    const repoName = repo;

    Array.from(this.cache.keys()).forEach((key) => {
      const matches =
        key.includes(`--repo:${repoStr}`) ||
        key.includes(`/${repoStr}/`) ||
        (key.includes(`owner=${owner}`) && key.includes(`name=${repoName}`));

      if (matches) {
        this.cache.delete(key);
      }
    });
  }

  /**
   * Get cache statistics for monitoring.
   *
   * @returns Current cache size and pending request count
   */
  getStats() {
    return {
      size: this.cache.size,
      pending: this.pendingRequests.size,
    };
  }

  /**
   * Clear all cached entries (useful for testing).
   */
  clear(): void {
    this.cache.clear();
    this.pendingRequests.clear();
  }
}

/** Global cache instance - singleton pattern */
export const ghCache = new GhCache();
// Force cache refresh 1774182206
